---
- block:
    - name: Download The Haskell Tool Stack
      uri:
        url: https://get.haskellstack.org/
        method: GET
        dest: "{{ shellcheck_stack_dl_path }}"
        creates: "{{ shellcheck_stack_dl_path }}"

    - name: Install The Haskell Tool Stack
      command: "sh {{ shellcheck_stack_dl_path }}"
      args:
        creates: "{{ shellcheck_stack_path }}"

    - name: Stack Setup
      command: "{{ shellcheck_stack_path }} setup"

- name: Install ShellCheck
  command: "{{ shellcheck_stack_path }} install ShellCheck"
  args:
    creates: "{{ shellcheck_stack_build_path }}"
