---
- name: Prepare pipelining
  hosts: all
  become: yes
  vars:
    ansible_ssh_pipelining: no
  tasks:
    - name: Disable requiretty for ansible_user
      lineinfile:
        dest: /etc/sudoers
        regexp: '^Defaults:{{ ansible_user }}\srequiretty'
        line: 'Defaults:{{ ansible_user }} requiretty'
        validate: 'visudo -cf %s'
        backup: yes

- name: Build gitlab-runner on CentOS
  hosts: all
  become: true
  roles:
    - name: common
      tags:
        - common

    - name: docker
      tags:
        - docker

    - name: gitlab-runner
      tags:
        - gitlab-runner

    - name: shellcheck
      tags:
        - shellcheck
