---
- name: pipelining対応用play
  hosts: all
  become: yes
  vars:
    ansible_ssh_pipelining: no
  tasks:
    - name: ansible_userに対するrequiretty設置を無効化
      lineinfile:
        dest: /etc/sudoers
        regexp: '^Defaults:{{ ansible_user }}\srequiretty'
        line: 'Defaults:{{ ansible_user }} requiretty'
        validate: 'visudo -cf %s'
        backup: yes

- name: gitlab-runnerをCentOS上に構築する
  hosts: all
  become: true
  roles:
    - name: docker
      tags:
        - docker
    - name: shellcheck
      tags:
        - shellcheck
