---
- name: Install common packages
  yum:
    name: "{{ item }}"
  with_items:
    - epel-release
    - git

- name: Install python pakages
  yum:
    name: python-pip

- name: Upgrade pip to latest
  pip:
    name: pip
    state: latest
