---
- name: Download one of the binaries for your system
  uri:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
    method: GET
    dest: "{{ gitlab_runner_path }}"
    creates: "{{ gitlab_runner_path }}"

- name: Give gitlab-runner permissions to execute
  file:
    path: "{{ gitlab_runner_path }}"
    mode: "u+x,g+x,o+x"

- name: GitLab CI user
  user:
    name: "{{ gitlab_runner_user }}"
    comment: "GitLab Runner"
    createhome: yes
    home: "{{ gitlab_runner_home }}"
    shell: "{{ gitlab_runner_shell }}"

- name: find gitlab-runner on services
  find:
    path: /etc/systemd/system/
    patterns: "gitlab-runner.service"
  register: gitlab_runner_existed

- name: Install gitlab-runner
  command: "{{ gitlab_runner_path }} install --user={{ gitlab_runner_user }} --working-directory={{ gitlab_runner_home }}"
  when: "gitlab_runner_existed.matched != 1"

- name: Start gitlab-runner
  service:
    name: gitlab-runner
    state: started
    enabled: true

- name: debug list all options with gitlab-runner regisgter
  command: "{{ gitlab_runner_path }} register --help"
  when: "gitlab_runner_debug == true"

- name: register gitlab-runner with gitlab
  command: "{{ gitlab_runner_path }} register"
  environment:
    CI_SERVER_URL: "{{ gitlab_runner_ci_server_url }}"
    CI_SERVER_TOKEN: "{{ gitlab_runner_token }}"
    RUNNER_NAME: "{{ gitlab_runner_name }}"
    REGISTER_NON_INTERACTIVE: true
    RUNNER_EXECUTOR: "{{ gitlab_runner_executor }}"
