---
- name: Appends domain definition to hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ gitlab_runner_ci_server_domain }}"
    line: "{{ gitlab_runner_ci_server_ip }}	{{ gitlab_runner_ci_server_domain }}"
    backup: yes
  when: "gitlab_runner_no_dns == true"

- name: Download one of the binaries for your system
  uri:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
    method: GET
    dest: "{{ gitlab_runner_path }}"
    creates: "{{ gitlab_runner_path }}"

- name: Give gitlab-runner permissions to execute
  file:
    path: "{{ gitlab_runner_path }}"
    mode: "u+x,g+x,o+x"

- name: GitLab CI user
  user:
    name: "{{ gitlab_runner_user }}"
    comment: "GitLab Runner"
    createhome: yes
    home: "{{ gitlab_runner_home }}"
    shell: "{{ gitlab_runner_shell }}"
    append: yes
    groups: dockerroot

- name: Install gitlab-runner
  command: "{{ gitlab_runner_path }} install --user={{ gitlab_runner_user }} --working-directory={{ gitlab_runner_home }}"
  args:
    creates: /etc/systemd/system/gitlab-runner.service

- name: Start gitlab-runner
  service:
    name: gitlab-runner
    state: started
    enabled: true

- name: debug list all options with gitlab-runner regisgter
  command: "{{ gitlab_runner_path }} register --help"
  when: "gitlab_runner_debug == true"

- name: register gitlab-runner with gitlab
  command: "{{ gitlab_runner_path }} register"
  environment:
    CI_SERVER_URL: "{{ gitlab_runner_ci_server_url }}"
    CI_SERVER_TOKEN: "{{ gitlab_runner_token }}"
    RUNNER_NAME: "{{ gitlab_runner_name }}"
    REGISTER_NON_INTERACTIVE: true
    RUNNER_EXECUTOR: "{{ gitlab_runner_executor }}"
